"""empty message

Revision ID: 7834adf4ed13
Revises: d8fe5910a33f
Create Date: 2023-06-18 19:37:29.356224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7834adf4ed13'
down_revision = 'd8fe5910a33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###